// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_frame.proto

package com.meux.icarbonx.proto;

public final class ProtobuffFrame {
    private ProtobuffFrame() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface RequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:PB_MEUMX.Request)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 命令 cmd
         * </pre>
         *
         * <code>required sint32 cmd = 1;</code>
         */
        boolean hasCmd();

        /**
         * <pre>
         * 命令 cmd
         * </pre>
         *
         * <code>required sint32 cmd = 1;</code>
         */
        int getCmd();

        /**
         * <pre>
         * 命令分支/子命令
         * </pre>
         *
         * <code>required sint32 sub = 2;</code>
         */
        boolean hasSub();

        /**
         * <pre>
         * 命令分支/子命令
         * </pre>
         *
         * <code>required sint32 sub = 2;</code>
         */
        int getSub();

        /**
         * <pre>
         * 数据 body
         * </pre>
         *
         * <code>optional bytes body = 3;</code>
         */
        boolean hasBody();

        /**
         * <pre>
         * 数据 body
         * </pre>
         *
         * <code>optional bytes body = 3;</code>
         */
        com.google.protobuf.ByteString getBody();
    }

    /**
     * <pre>
     * 请求消息体
     * </pre>
     * <p>
     * Protobuf type {@code PB_MEUMX.Request}
     */
    public static final class Request extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:PB_MEUMX.Request)
            RequestOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Request.newBuilder() to construct.
        private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Request() {
            cmd_ = 0;
            sub_ = 0;
            body_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Request(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            cmd_ = input.readSInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            sub_ = input.readSInt32();
                            break;
                        }
                        case 26: {
                            bitField0_ |= 0x00000004;
                            body_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.meux.icarbonx.proto.ProtobuffFrame.internal_static_PB_MEUMX_Request_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.meux.icarbonx.proto.ProtobuffFrame.internal_static_PB_MEUMX_Request_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.meux.icarbonx.proto.ProtobuffFrame.Request.class, com.meux.icarbonx.proto.ProtobuffFrame.Request.Builder.class);
        }

        private int bitField0_;
        public static final int CMD_FIELD_NUMBER = 1;
        private int cmd_;

        /**
         * <pre>
         * 命令 cmd
         * </pre>
         *
         * <code>required sint32 cmd = 1;</code>
         */
        public boolean hasCmd() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <pre>
         * 命令 cmd
         * </pre>
         *
         * <code>required sint32 cmd = 1;</code>
         */
        public int getCmd() {
            return cmd_;
        }

        public static final int SUB_FIELD_NUMBER = 2;
        private int sub_;

        /**
         * <pre>
         * 命令分支/子命令
         * </pre>
         *
         * <code>required sint32 sub = 2;</code>
         */
        public boolean hasSub() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <pre>
         * 命令分支/子命令
         * </pre>
         *
         * <code>required sint32 sub = 2;</code>
         */
        public int getSub() {
            return sub_;
        }

        public static final int BODY_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString body_;

        /**
         * <pre>
         * 数据 body
         * </pre>
         *
         * <code>optional bytes body = 3;</code>
         */
        public boolean hasBody() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <pre>
         * 数据 body
         * </pre>
         *
         * <code>optional bytes body = 3;</code>
         */
        public com.google.protobuf.ByteString getBody() {
            return body_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasCmd()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasSub()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeSInt32(1, cmd_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeSInt32(2, sub_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, body_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt32Size(1, cmd_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt32Size(2, sub_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, body_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.meux.icarbonx.proto.ProtobuffFrame.Request)) {
                return super.equals(obj);
            }
            com.meux.icarbonx.proto.ProtobuffFrame.Request other = (com.meux.icarbonx.proto.ProtobuffFrame.Request) obj;

            boolean result = true;
            result = result && (hasCmd() == other.hasCmd());
            if (hasCmd()) {
                result = result && (getCmd()
                        == other.getCmd());
            }
            result = result && (hasSub() == other.hasSub());
            if (hasSub()) {
                result = result && (getSub()
                        == other.getSub());
            }
            result = result && (hasBody() == other.hasBody());
            if (hasBody()) {
                result = result && getBody()
                        .equals(other.getBody());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasCmd()) {
                hash = (37 * hash) + CMD_FIELD_NUMBER;
                hash = (53 * hash) + getCmd();
            }
            if (hasSub()) {
                hash = (37 * hash) + SUB_FIELD_NUMBER;
                hash = (53 * hash) + getSub();
            }
            if (hasBody()) {
                hash = (37 * hash) + BODY_FIELD_NUMBER;
                hash = (53 * hash) + getBody().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Request parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Request parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Request parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Request parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Request parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Request parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Request parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Request parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Request parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Request parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Request parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Request parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.meux.icarbonx.proto.ProtobuffFrame.Request prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 请求消息体
         * </pre>
         * <p>
         * Protobuf type {@code PB_MEUMX.Request}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:PB_MEUMX.Request)
                com.meux.icarbonx.proto.ProtobuffFrame.RequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.meux.icarbonx.proto.ProtobuffFrame.internal_static_PB_MEUMX_Request_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.meux.icarbonx.proto.ProtobuffFrame.internal_static_PB_MEUMX_Request_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.meux.icarbonx.proto.ProtobuffFrame.Request.class, com.meux.icarbonx.proto.ProtobuffFrame.Request.Builder.class);
            }

            // Construct using com.meux.icarbonx.proto.ProtobuffFrame.Request.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                cmd_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                sub_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                body_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.meux.icarbonx.proto.ProtobuffFrame.internal_static_PB_MEUMX_Request_descriptor;
            }

            public com.meux.icarbonx.proto.ProtobuffFrame.Request getDefaultInstanceForType() {
                return com.meux.icarbonx.proto.ProtobuffFrame.Request.getDefaultInstance();
            }

            public com.meux.icarbonx.proto.ProtobuffFrame.Request build() {
                com.meux.icarbonx.proto.ProtobuffFrame.Request result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.meux.icarbonx.proto.ProtobuffFrame.Request buildPartial() {
                com.meux.icarbonx.proto.ProtobuffFrame.Request result = new com.meux.icarbonx.proto.ProtobuffFrame.Request(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.cmd_ = cmd_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.sub_ = sub_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.body_ = body_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.meux.icarbonx.proto.ProtobuffFrame.Request) {
                    return mergeFrom((com.meux.icarbonx.proto.ProtobuffFrame.Request) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.meux.icarbonx.proto.ProtobuffFrame.Request other) {
                if (other == com.meux.icarbonx.proto.ProtobuffFrame.Request.getDefaultInstance()) return this;
                if (other.hasCmd()) {
                    setCmd(other.getCmd());
                }
                if (other.hasSub()) {
                    setSub(other.getSub());
                }
                if (other.hasBody()) {
                    setBody(other.getBody());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                if (!hasCmd()) {
                    return false;
                }
                if (!hasSub()) {
                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.meux.icarbonx.proto.ProtobuffFrame.Request parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.meux.icarbonx.proto.ProtobuffFrame.Request) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private int cmd_;

            /**
             * <pre>
             * 命令 cmd
             * </pre>
             *
             * <code>required sint32 cmd = 1;</code>
             */
            public boolean hasCmd() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <pre>
             * 命令 cmd
             * </pre>
             *
             * <code>required sint32 cmd = 1;</code>
             */
            public int getCmd() {
                return cmd_;
            }

            /**
             * <pre>
             * 命令 cmd
             * </pre>
             *
             * <code>required sint32 cmd = 1;</code>
             */
            public Builder setCmd(int value) {
                bitField0_ |= 0x00000001;
                cmd_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 命令 cmd
             * </pre>
             *
             * <code>required sint32 cmd = 1;</code>
             */
            public Builder clearCmd() {
                bitField0_ = (bitField0_ & ~0x00000001);
                cmd_ = 0;
                onChanged();
                return this;
            }

            private int sub_;

            /**
             * <pre>
             * 命令分支/子命令
             * </pre>
             *
             * <code>required sint32 sub = 2;</code>
             */
            public boolean hasSub() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <pre>
             * 命令分支/子命令
             * </pre>
             *
             * <code>required sint32 sub = 2;</code>
             */
            public int getSub() {
                return sub_;
            }

            /**
             * <pre>
             * 命令分支/子命令
             * </pre>
             *
             * <code>required sint32 sub = 2;</code>
             */
            public Builder setSub(int value) {
                bitField0_ |= 0x00000002;
                sub_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 命令分支/子命令
             * </pre>
             *
             * <code>required sint32 sub = 2;</code>
             */
            public Builder clearSub() {
                bitField0_ = (bitField0_ & ~0x00000002);
                sub_ = 0;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <pre>
             * 数据 body
             * </pre>
             *
             * <code>optional bytes body = 3;</code>
             */
            public boolean hasBody() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <pre>
             * 数据 body
             * </pre>
             *
             * <code>optional bytes body = 3;</code>
             */
            public com.google.protobuf.ByteString getBody() {
                return body_;
            }

            /**
             * <pre>
             * 数据 body
             * </pre>
             *
             * <code>optional bytes body = 3;</code>
             */
            public Builder setBody(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                body_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 数据 body
             * </pre>
             *
             * <code>optional bytes body = 3;</code>
             */
            public Builder clearBody() {
                bitField0_ = (bitField0_ & ~0x00000004);
                body_ = getDefaultInstance().getBody();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:PB_MEUMX.Request)
        }

        // @@protoc_insertion_point(class_scope:PB_MEUMX.Request)
        private static final com.meux.icarbonx.proto.ProtobuffFrame.Request DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.meux.icarbonx.proto.ProtobuffFrame.Request();
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Request getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<Request>
                PARSER = new com.google.protobuf.AbstractParser<Request>() {
            public Request parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Request(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Request> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Request> getParserForType() {
            return PARSER;
        }

        public com.meux.icarbonx.proto.ProtobuffFrame.Request getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface ResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:PB_MEUMX.Response)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 命令 cmd
         * </pre>
         *
         * <code>required sint32 cmd = 1;</code>
         */
        boolean hasCmd();

        /**
         * <pre>
         * 命令 cmd
         * </pre>
         *
         * <code>required sint32 cmd = 1;</code>
         */
        int getCmd();

        /**
         * <pre>
         * 命令分支/子命令
         * </pre>
         *
         * <code>required sint32 sub = 2;</code>
         */
        boolean hasSub();

        /**
         * <pre>
         * 命令分支/子命令
         * </pre>
         *
         * <code>required sint32 sub = 2;</code>
         */
        int getSub();

        /**
         * <pre>
         * 状态码 code 0 正常
         * </pre>
         *
         * <code>required sint32 code = 3;</code>
         */
        boolean hasCode();

        /**
         * <pre>
         * 状态码 code 0 正常
         * </pre>
         *
         * <code>required sint32 code = 3;</code>
         */
        int getCode();

        /**
         * <pre>
         * 数据 body
         * </pre>
         *
         * <code>optional bytes body = 4;</code>
         */
        boolean hasBody();

        /**
         * <pre>
         * 数据 body
         * </pre>
         *
         * <code>optional bytes body = 4;</code>
         */
        com.google.protobuf.ByteString getBody();
    }

    /**
     * <pre>
     * 响应消息体
     * </pre>
     * <p>
     * Protobuf type {@code PB_MEUMX.Response}
     */
    public static final class Response extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:PB_MEUMX.Response)
            ResponseOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Response.newBuilder() to construct.
        private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Response() {
            cmd_ = 0;
            sub_ = 0;
            code_ = 0;
            body_ = com.google.protobuf.ByteString.EMPTY;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Response(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            bitField0_ |= 0x00000001;
                            cmd_ = input.readSInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            sub_ = input.readSInt32();
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            code_ = input.readSInt32();
                            break;
                        }
                        case 34: {
                            bitField0_ |= 0x00000008;
                            body_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.meux.icarbonx.proto.ProtobuffFrame.internal_static_PB_MEUMX_Response_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.meux.icarbonx.proto.ProtobuffFrame.internal_static_PB_MEUMX_Response_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.meux.icarbonx.proto.ProtobuffFrame.Response.class, com.meux.icarbonx.proto.ProtobuffFrame.Response.Builder.class);
        }

        private int bitField0_;
        public static final int CMD_FIELD_NUMBER = 1;
        private int cmd_;

        /**
         * <pre>
         * 命令 cmd
         * </pre>
         *
         * <code>required sint32 cmd = 1;</code>
         */
        public boolean hasCmd() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <pre>
         * 命令 cmd
         * </pre>
         *
         * <code>required sint32 cmd = 1;</code>
         */
        public int getCmd() {
            return cmd_;
        }

        public static final int SUB_FIELD_NUMBER = 2;
        private int sub_;

        /**
         * <pre>
         * 命令分支/子命令
         * </pre>
         *
         * <code>required sint32 sub = 2;</code>
         */
        public boolean hasSub() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <pre>
         * 命令分支/子命令
         * </pre>
         *
         * <code>required sint32 sub = 2;</code>
         */
        public int getSub() {
            return sub_;
        }

        public static final int CODE_FIELD_NUMBER = 3;
        private int code_;

        /**
         * <pre>
         * 状态码 code 0 正常
         * </pre>
         *
         * <code>required sint32 code = 3;</code>
         */
        public boolean hasCode() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <pre>
         * 状态码 code 0 正常
         * </pre>
         *
         * <code>required sint32 code = 3;</code>
         */
        public int getCode() {
            return code_;
        }

        public static final int BODY_FIELD_NUMBER = 4;
        private com.google.protobuf.ByteString body_;

        /**
         * <pre>
         * 数据 body
         * </pre>
         *
         * <code>optional bytes body = 4;</code>
         */
        public boolean hasBody() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <pre>
         * 数据 body
         * </pre>
         *
         * <code>optional bytes body = 4;</code>
         */
        public com.google.protobuf.ByteString getBody() {
            return body_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasCmd()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasSub()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasCode()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeSInt32(1, cmd_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeSInt32(2, sub_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeSInt32(3, code_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeBytes(4, body_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt32Size(1, cmd_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt32Size(2, sub_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeSInt32Size(3, code_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, body_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.meux.icarbonx.proto.ProtobuffFrame.Response)) {
                return super.equals(obj);
            }
            com.meux.icarbonx.proto.ProtobuffFrame.Response other = (com.meux.icarbonx.proto.ProtobuffFrame.Response) obj;

            boolean result = true;
            result = result && (hasCmd() == other.hasCmd());
            if (hasCmd()) {
                result = result && (getCmd()
                        == other.getCmd());
            }
            result = result && (hasSub() == other.hasSub());
            if (hasSub()) {
                result = result && (getSub()
                        == other.getSub());
            }
            result = result && (hasCode() == other.hasCode());
            if (hasCode()) {
                result = result && (getCode()
                        == other.getCode());
            }
            result = result && (hasBody() == other.hasBody());
            if (hasBody()) {
                result = result && getBody()
                        .equals(other.getBody());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasCmd()) {
                hash = (37 * hash) + CMD_FIELD_NUMBER;
                hash = (53 * hash) + getCmd();
            }
            if (hasSub()) {
                hash = (37 * hash) + SUB_FIELD_NUMBER;
                hash = (53 * hash) + getSub();
            }
            if (hasCode()) {
                hash = (37 * hash) + CODE_FIELD_NUMBER;
                hash = (53 * hash) + getCode();
            }
            if (hasBody()) {
                hash = (37 * hash) + BODY_FIELD_NUMBER;
                hash = (53 * hash) + getBody().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Response parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Response parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Response parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Response parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Response parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Response parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Response parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Response parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Response parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Response parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Response parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Response parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.meux.icarbonx.proto.ProtobuffFrame.Response prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 响应消息体
         * </pre>
         * <p>
         * Protobuf type {@code PB_MEUMX.Response}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:PB_MEUMX.Response)
                com.meux.icarbonx.proto.ProtobuffFrame.ResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.meux.icarbonx.proto.ProtobuffFrame.internal_static_PB_MEUMX_Response_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.meux.icarbonx.proto.ProtobuffFrame.internal_static_PB_MEUMX_Response_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.meux.icarbonx.proto.ProtobuffFrame.Response.class, com.meux.icarbonx.proto.ProtobuffFrame.Response.Builder.class);
            }

            // Construct using com.meux.icarbonx.proto.ProtobuffFrame.Response.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                cmd_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                sub_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                code_ = 0;
                bitField0_ = (bitField0_ & ~0x00000004);
                body_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000008);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.meux.icarbonx.proto.ProtobuffFrame.internal_static_PB_MEUMX_Response_descriptor;
            }

            public com.meux.icarbonx.proto.ProtobuffFrame.Response getDefaultInstanceForType() {
                return com.meux.icarbonx.proto.ProtobuffFrame.Response.getDefaultInstance();
            }

            public com.meux.icarbonx.proto.ProtobuffFrame.Response build() {
                com.meux.icarbonx.proto.ProtobuffFrame.Response result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.meux.icarbonx.proto.ProtobuffFrame.Response buildPartial() {
                com.meux.icarbonx.proto.ProtobuffFrame.Response result = new com.meux.icarbonx.proto.ProtobuffFrame.Response(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.cmd_ = cmd_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.sub_ = sub_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.code_ = code_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.body_ = body_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.meux.icarbonx.proto.ProtobuffFrame.Response) {
                    return mergeFrom((com.meux.icarbonx.proto.ProtobuffFrame.Response) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.meux.icarbonx.proto.ProtobuffFrame.Response other) {
                if (other == com.meux.icarbonx.proto.ProtobuffFrame.Response.getDefaultInstance()) return this;
                if (other.hasCmd()) {
                    setCmd(other.getCmd());
                }
                if (other.hasSub()) {
                    setSub(other.getSub());
                }
                if (other.hasCode()) {
                    setCode(other.getCode());
                }
                if (other.hasBody()) {
                    setBody(other.getBody());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                if (!hasCmd()) {
                    return false;
                }
                if (!hasSub()) {
                    return false;
                }
                if (!hasCode()) {
                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.meux.icarbonx.proto.ProtobuffFrame.Response parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.meux.icarbonx.proto.ProtobuffFrame.Response) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private int cmd_;

            /**
             * <pre>
             * 命令 cmd
             * </pre>
             *
             * <code>required sint32 cmd = 1;</code>
             */
            public boolean hasCmd() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <pre>
             * 命令 cmd
             * </pre>
             *
             * <code>required sint32 cmd = 1;</code>
             */
            public int getCmd() {
                return cmd_;
            }

            /**
             * <pre>
             * 命令 cmd
             * </pre>
             *
             * <code>required sint32 cmd = 1;</code>
             */
            public Builder setCmd(int value) {
                bitField0_ |= 0x00000001;
                cmd_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 命令 cmd
             * </pre>
             *
             * <code>required sint32 cmd = 1;</code>
             */
            public Builder clearCmd() {
                bitField0_ = (bitField0_ & ~0x00000001);
                cmd_ = 0;
                onChanged();
                return this;
            }

            private int sub_;

            /**
             * <pre>
             * 命令分支/子命令
             * </pre>
             *
             * <code>required sint32 sub = 2;</code>
             */
            public boolean hasSub() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <pre>
             * 命令分支/子命令
             * </pre>
             *
             * <code>required sint32 sub = 2;</code>
             */
            public int getSub() {
                return sub_;
            }

            /**
             * <pre>
             * 命令分支/子命令
             * </pre>
             *
             * <code>required sint32 sub = 2;</code>
             */
            public Builder setSub(int value) {
                bitField0_ |= 0x00000002;
                sub_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 命令分支/子命令
             * </pre>
             *
             * <code>required sint32 sub = 2;</code>
             */
            public Builder clearSub() {
                bitField0_ = (bitField0_ & ~0x00000002);
                sub_ = 0;
                onChanged();
                return this;
            }

            private int code_;

            /**
             * <pre>
             * 状态码 code 0 正常
             * </pre>
             *
             * <code>required sint32 code = 3;</code>
             */
            public boolean hasCode() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <pre>
             * 状态码 code 0 正常
             * </pre>
             *
             * <code>required sint32 code = 3;</code>
             */
            public int getCode() {
                return code_;
            }

            /**
             * <pre>
             * 状态码 code 0 正常
             * </pre>
             *
             * <code>required sint32 code = 3;</code>
             */
            public Builder setCode(int value) {
                bitField0_ |= 0x00000004;
                code_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 状态码 code 0 正常
             * </pre>
             *
             * <code>required sint32 code = 3;</code>
             */
            public Builder clearCode() {
                bitField0_ = (bitField0_ & ~0x00000004);
                code_ = 0;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <pre>
             * 数据 body
             * </pre>
             *
             * <code>optional bytes body = 4;</code>
             */
            public boolean hasBody() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <pre>
             * 数据 body
             * </pre>
             *
             * <code>optional bytes body = 4;</code>
             */
            public com.google.protobuf.ByteString getBody() {
                return body_;
            }

            /**
             * <pre>
             * 数据 body
             * </pre>
             *
             * <code>optional bytes body = 4;</code>
             */
            public Builder setBody(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                body_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 数据 body
             * </pre>
             *
             * <code>optional bytes body = 4;</code>
             */
            public Builder clearBody() {
                bitField0_ = (bitField0_ & ~0x00000008);
                body_ = getDefaultInstance().getBody();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:PB_MEUMX.Response)
        }

        // @@protoc_insertion_point(class_scope:PB_MEUMX.Response)
        private static final com.meux.icarbonx.proto.ProtobuffFrame.Response DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.meux.icarbonx.proto.ProtobuffFrame.Response();
        }

        public static com.meux.icarbonx.proto.ProtobuffFrame.Response getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<Response>
                PARSER = new com.google.protobuf.AbstractParser<Response>() {
            public Response parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Response(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Response> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Response> getParserForType() {
            return PARSER;
        }

        public com.meux.icarbonx.proto.ProtobuffFrame.Response getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_PB_MEUMX_Request_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_PB_MEUMX_Request_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_PB_MEUMX_Response_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_PB_MEUMX_Response_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\016pb_frame.proto\022\010PB_MEUMX\"1\n\007Request\022\013\n" +
                        "\003cmd\030\001 \002(\021\022\013\n\003sub\030\002 \002(\021\022\014\n\004body\030\003 \001(\014\"@\n" +
                        "\010Response\022\013\n\003cmd\030\001 \002(\021\022\013\n\003sub\030\002 \002(\021\022\014\n\004c" +
                        "ode\030\003 \002(\021\022\014\n\004body\030\004 \001(\014B)\n\027com.meux.icar" +
                        "bonx.protoB\016ProtobuffFrame"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_PB_MEUMX_Request_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_PB_MEUMX_Request_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_PB_MEUMX_Request_descriptor,
                new java.lang.String[]{"Cmd", "Sub", "Body",});
        internal_static_PB_MEUMX_Response_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_PB_MEUMX_Response_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_PB_MEUMX_Response_descriptor,
                new java.lang.String[]{"Cmd", "Sub", "Code", "Body",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
