// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_serverconfig.proto

package com.meux.icarbonx.proto;

public final class ProtoServerConf {
    private ProtoServerConf() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface FileUploadOrBuilder extends
            // @@protoc_insertion_point(interface_extends:PB_MEUMX.FileUpload)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
         */
        java.util.List<com.meux.icarbonx.proto.ProtoServerConf.MultiFile>
        getMultiFilesList();

        /**
         * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
         */
        com.meux.icarbonx.proto.ProtoServerConf.MultiFile getMultiFiles(int index);

        /**
         * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
         */
        int getMultiFilesCount();

        /**
         * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
         */
        java.util.List<? extends com.meux.icarbonx.proto.ProtoServerConf.MultiFileOrBuilder>
        getMultiFilesOrBuilderList();

        /**
         * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
         */
        com.meux.icarbonx.proto.ProtoServerConf.MultiFileOrBuilder getMultiFilesOrBuilder(
                int index);
    }

    /**
     * <pre>
     * 配置文件
     * </pre>
     * <p>
     * Protobuf type {@code PB_MEUMX.FileUpload}
     */
    public static final class FileUpload extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:PB_MEUMX.FileUpload)
            FileUploadOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use FileUpload.newBuilder() to construct.
        private FileUpload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private FileUpload() {
            multiFiles_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private FileUpload(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                multiFiles_ = new java.util.ArrayList<com.meux.icarbonx.proto.ProtoServerConf.MultiFile>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            multiFiles_.add(
                                    input.readMessage(com.meux.icarbonx.proto.ProtoServerConf.MultiFile.PARSER, extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    multiFiles_ = java.util.Collections.unmodifiableList(multiFiles_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.meux.icarbonx.proto.ProtoServerConf.internal_static_PB_MEUMX_FileUpload_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.meux.icarbonx.proto.ProtoServerConf.internal_static_PB_MEUMX_FileUpload_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.meux.icarbonx.proto.ProtoServerConf.FileUpload.class, com.meux.icarbonx.proto.ProtoServerConf.FileUpload.Builder.class);
        }

        public static final int MULTIFILES_FIELD_NUMBER = 1;
        private java.util.List<com.meux.icarbonx.proto.ProtoServerConf.MultiFile> multiFiles_;

        /**
         * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
         */
        public java.util.List<com.meux.icarbonx.proto.ProtoServerConf.MultiFile> getMultiFilesList() {
            return multiFiles_;
        }

        /**
         * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
         */
        public java.util.List<? extends com.meux.icarbonx.proto.ProtoServerConf.MultiFileOrBuilder>
        getMultiFilesOrBuilderList() {
            return multiFiles_;
        }

        /**
         * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
         */
        public int getMultiFilesCount() {
            return multiFiles_.size();
        }

        /**
         * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
         */
        public com.meux.icarbonx.proto.ProtoServerConf.MultiFile getMultiFiles(int index) {
            return multiFiles_.get(index);
        }

        /**
         * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
         */
        public com.meux.icarbonx.proto.ProtoServerConf.MultiFileOrBuilder getMultiFilesOrBuilder(
                int index) {
            return multiFiles_.get(index);
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            for (int i = 0; i < getMultiFilesCount(); i++) {
                if (!getMultiFiles(i).isInitialized()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            for (int i = 0; i < multiFiles_.size(); i++) {
                output.writeMessage(1, multiFiles_.get(i));
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < multiFiles_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, multiFiles_.get(i));
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.meux.icarbonx.proto.ProtoServerConf.FileUpload)) {
                return super.equals(obj);
            }
            com.meux.icarbonx.proto.ProtoServerConf.FileUpload other = (com.meux.icarbonx.proto.ProtoServerConf.FileUpload) obj;

            boolean result = true;
            result = result && getMultiFilesList()
                    .equals(other.getMultiFilesList());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (getMultiFilesCount() > 0) {
                hash = (37 * hash) + MULTIFILES_FIELD_NUMBER;
                hash = (53 * hash) + getMultiFilesList().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.FileUpload parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.FileUpload parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.FileUpload parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.FileUpload parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.FileUpload parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.FileUpload parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.FileUpload parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.FileUpload parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.FileUpload parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.FileUpload parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.FileUpload parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.FileUpload parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.meux.icarbonx.proto.ProtoServerConf.FileUpload prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 配置文件
         * </pre>
         * <p>
         * Protobuf type {@code PB_MEUMX.FileUpload}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:PB_MEUMX.FileUpload)
                com.meux.icarbonx.proto.ProtoServerConf.FileUploadOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.meux.icarbonx.proto.ProtoServerConf.internal_static_PB_MEUMX_FileUpload_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.meux.icarbonx.proto.ProtoServerConf.internal_static_PB_MEUMX_FileUpload_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.meux.icarbonx.proto.ProtoServerConf.FileUpload.class, com.meux.icarbonx.proto.ProtoServerConf.FileUpload.Builder.class);
            }

            // Construct using com.meux.icarbonx.proto.ProtoServerConf.FileUpload.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getMultiFilesFieldBuilder();
                }
            }

            public Builder clear() {
                super.clear();
                if (multiFilesBuilder_ == null) {
                    multiFiles_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    multiFilesBuilder_.clear();
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.meux.icarbonx.proto.ProtoServerConf.internal_static_PB_MEUMX_FileUpload_descriptor;
            }

            public com.meux.icarbonx.proto.ProtoServerConf.FileUpload getDefaultInstanceForType() {
                return com.meux.icarbonx.proto.ProtoServerConf.FileUpload.getDefaultInstance();
            }

            public com.meux.icarbonx.proto.ProtoServerConf.FileUpload build() {
                com.meux.icarbonx.proto.ProtoServerConf.FileUpload result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.meux.icarbonx.proto.ProtoServerConf.FileUpload buildPartial() {
                com.meux.icarbonx.proto.ProtoServerConf.FileUpload result = new com.meux.icarbonx.proto.ProtoServerConf.FileUpload(this);
                int from_bitField0_ = bitField0_;
                if (multiFilesBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001)) {
                        multiFiles_ = java.util.Collections.unmodifiableList(multiFiles_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.multiFiles_ = multiFiles_;
                } else {
                    result.multiFiles_ = multiFilesBuilder_.build();
                }
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.meux.icarbonx.proto.ProtoServerConf.FileUpload) {
                    return mergeFrom((com.meux.icarbonx.proto.ProtoServerConf.FileUpload) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.meux.icarbonx.proto.ProtoServerConf.FileUpload other) {
                if (other == com.meux.icarbonx.proto.ProtoServerConf.FileUpload.getDefaultInstance()) return this;
                if (multiFilesBuilder_ == null) {
                    if (!other.multiFiles_.isEmpty()) {
                        if (multiFiles_.isEmpty()) {
                            multiFiles_ = other.multiFiles_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureMultiFilesIsMutable();
                            multiFiles_.addAll(other.multiFiles_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.multiFiles_.isEmpty()) {
                        if (multiFilesBuilder_.isEmpty()) {
                            multiFilesBuilder_.dispose();
                            multiFilesBuilder_ = null;
                            multiFiles_ = other.multiFiles_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            multiFilesBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getMultiFilesFieldBuilder() : null;
                        } else {
                            multiFilesBuilder_.addAllMessages(other.multiFiles_);
                        }
                    }
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                for (int i = 0; i < getMultiFilesCount(); i++) {
                    if (!getMultiFiles(i).isInitialized()) {
                        return false;
                    }
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.meux.icarbonx.proto.ProtoServerConf.FileUpload parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.meux.icarbonx.proto.ProtoServerConf.FileUpload) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private java.util.List<com.meux.icarbonx.proto.ProtoServerConf.MultiFile> multiFiles_ =
                    java.util.Collections.emptyList();

            private void ensureMultiFilesIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    multiFiles_ = new java.util.ArrayList<com.meux.icarbonx.proto.ProtoServerConf.MultiFile>(multiFiles_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    com.meux.icarbonx.proto.ProtoServerConf.MultiFile, com.meux.icarbonx.proto.ProtoServerConf.MultiFile.Builder, com.meux.icarbonx.proto.ProtoServerConf.MultiFileOrBuilder> multiFilesBuilder_;

            /**
             * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
             */
            public java.util.List<com.meux.icarbonx.proto.ProtoServerConf.MultiFile> getMultiFilesList() {
                if (multiFilesBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(multiFiles_);
                } else {
                    return multiFilesBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
             */
            public int getMultiFilesCount() {
                if (multiFilesBuilder_ == null) {
                    return multiFiles_.size();
                } else {
                    return multiFilesBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
             */
            public com.meux.icarbonx.proto.ProtoServerConf.MultiFile getMultiFiles(int index) {
                if (multiFilesBuilder_ == null) {
                    return multiFiles_.get(index);
                } else {
                    return multiFilesBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
             */
            public Builder setMultiFiles(
                    int index, com.meux.icarbonx.proto.ProtoServerConf.MultiFile value) {
                if (multiFilesBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureMultiFilesIsMutable();
                    multiFiles_.set(index, value);
                    onChanged();
                } else {
                    multiFilesBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
             */
            public Builder setMultiFiles(
                    int index, com.meux.icarbonx.proto.ProtoServerConf.MultiFile.Builder builderForValue) {
                if (multiFilesBuilder_ == null) {
                    ensureMultiFilesIsMutable();
                    multiFiles_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    multiFilesBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
             */
            public Builder addMultiFiles(com.meux.icarbonx.proto.ProtoServerConf.MultiFile value) {
                if (multiFilesBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureMultiFilesIsMutable();
                    multiFiles_.add(value);
                    onChanged();
                } else {
                    multiFilesBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
             */
            public Builder addMultiFiles(
                    int index, com.meux.icarbonx.proto.ProtoServerConf.MultiFile value) {
                if (multiFilesBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureMultiFilesIsMutable();
                    multiFiles_.add(index, value);
                    onChanged();
                } else {
                    multiFilesBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
             */
            public Builder addMultiFiles(
                    com.meux.icarbonx.proto.ProtoServerConf.MultiFile.Builder builderForValue) {
                if (multiFilesBuilder_ == null) {
                    ensureMultiFilesIsMutable();
                    multiFiles_.add(builderForValue.build());
                    onChanged();
                } else {
                    multiFilesBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
             */
            public Builder addMultiFiles(
                    int index, com.meux.icarbonx.proto.ProtoServerConf.MultiFile.Builder builderForValue) {
                if (multiFilesBuilder_ == null) {
                    ensureMultiFilesIsMutable();
                    multiFiles_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    multiFilesBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
             */
            public Builder addAllMultiFiles(
                    java.lang.Iterable<? extends com.meux.icarbonx.proto.ProtoServerConf.MultiFile> values) {
                if (multiFilesBuilder_ == null) {
                    ensureMultiFilesIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, multiFiles_);
                    onChanged();
                } else {
                    multiFilesBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
             */
            public Builder clearMultiFiles() {
                if (multiFilesBuilder_ == null) {
                    multiFiles_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    multiFilesBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
             */
            public Builder removeMultiFiles(int index) {
                if (multiFilesBuilder_ == null) {
                    ensureMultiFilesIsMutable();
                    multiFiles_.remove(index);
                    onChanged();
                } else {
                    multiFilesBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
             */
            public com.meux.icarbonx.proto.ProtoServerConf.MultiFile.Builder getMultiFilesBuilder(
                    int index) {
                return getMultiFilesFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
             */
            public com.meux.icarbonx.proto.ProtoServerConf.MultiFileOrBuilder getMultiFilesOrBuilder(
                    int index) {
                if (multiFilesBuilder_ == null) {
                    return multiFiles_.get(index);
                } else {
                    return multiFilesBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
             */
            public java.util.List<? extends com.meux.icarbonx.proto.ProtoServerConf.MultiFileOrBuilder>
            getMultiFilesOrBuilderList() {
                if (multiFilesBuilder_ != null) {
                    return multiFilesBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(multiFiles_);
                }
            }

            /**
             * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
             */
            public com.meux.icarbonx.proto.ProtoServerConf.MultiFile.Builder addMultiFilesBuilder() {
                return getMultiFilesFieldBuilder().addBuilder(
                        com.meux.icarbonx.proto.ProtoServerConf.MultiFile.getDefaultInstance());
            }

            /**
             * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
             */
            public com.meux.icarbonx.proto.ProtoServerConf.MultiFile.Builder addMultiFilesBuilder(
                    int index) {
                return getMultiFilesFieldBuilder().addBuilder(
                        index, com.meux.icarbonx.proto.ProtoServerConf.MultiFile.getDefaultInstance());
            }

            /**
             * <code>repeated .PB_MEUMX.MultiFile multiFiles = 1;</code>
             */
            public java.util.List<com.meux.icarbonx.proto.ProtoServerConf.MultiFile.Builder>
            getMultiFilesBuilderList() {
                return getMultiFilesFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    com.meux.icarbonx.proto.ProtoServerConf.MultiFile, com.meux.icarbonx.proto.ProtoServerConf.MultiFile.Builder, com.meux.icarbonx.proto.ProtoServerConf.MultiFileOrBuilder>
            getMultiFilesFieldBuilder() {
                if (multiFilesBuilder_ == null) {
                    multiFilesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            com.meux.icarbonx.proto.ProtoServerConf.MultiFile, com.meux.icarbonx.proto.ProtoServerConf.MultiFile.Builder, com.meux.icarbonx.proto.ProtoServerConf.MultiFileOrBuilder>(
                            multiFiles_,
                            ((bitField0_ & 0x00000001) == 0x00000001),
                            getParentForChildren(),
                            isClean());
                    multiFiles_ = null;
                }
                return multiFilesBuilder_;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:PB_MEUMX.FileUpload)
        }

        // @@protoc_insertion_point(class_scope:PB_MEUMX.FileUpload)
        private static final com.meux.icarbonx.proto.ProtoServerConf.FileUpload DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.meux.icarbonx.proto.ProtoServerConf.FileUpload();
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.FileUpload getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<FileUpload>
                PARSER = new com.google.protobuf.AbstractParser<FileUpload>() {
            public FileUpload parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new FileUpload(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<FileUpload> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<FileUpload> getParserForType() {
            return PARSER;
        }

        public com.meux.icarbonx.proto.ProtoServerConf.FileUpload getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface MultiFileOrBuilder extends
            // @@protoc_insertion_point(interface_extends:PB_MEUMX.MultiFile)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required bytes file = 1;</code>
         */
        boolean hasFile();

        /**
         * <code>required bytes file = 1;</code>
         */
        com.google.protobuf.ByteString getFile();

        /**
         * <pre>
         * 文件名
         * </pre>
         *
         * <code>required string name = 2;</code>
         */
        boolean hasName();

        /**
         * <pre>
         * 文件名
         * </pre>
         *
         * <code>required string name = 2;</code>
         */
        java.lang.String getName();

        /**
         * <pre>
         * 文件名
         * </pre>
         *
         * <code>required string name = 2;</code>
         */
        com.google.protobuf.ByteString
        getNameBytes();
    }

    /**
     * Protobuf type {@code PB_MEUMX.MultiFile}
     */
    public static final class MultiFile extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:PB_MEUMX.MultiFile)
            MultiFileOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use MultiFile.newBuilder() to construct.
        private MultiFile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private MultiFile() {
            file_ = com.google.protobuf.ByteString.EMPTY;
            name_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private MultiFile(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            file_ = input.readBytes();
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            name_ = bs;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.meux.icarbonx.proto.ProtoServerConf.internal_static_PB_MEUMX_MultiFile_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.meux.icarbonx.proto.ProtoServerConf.internal_static_PB_MEUMX_MultiFile_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.meux.icarbonx.proto.ProtoServerConf.MultiFile.class, com.meux.icarbonx.proto.ProtoServerConf.MultiFile.Builder.class);
        }

        private int bitField0_;
        public static final int FILE_FIELD_NUMBER = 1;
        private com.google.protobuf.ByteString file_;

        /**
         * <code>required bytes file = 1;</code>
         */
        public boolean hasFile() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required bytes file = 1;</code>
         */
        public com.google.protobuf.ByteString getFile() {
            return file_;
        }

        public static final int NAME_FIELD_NUMBER = 2;
        private volatile java.lang.Object name_;

        /**
         * <pre>
         * 文件名
         * </pre>
         *
         * <code>required string name = 2;</code>
         */
        public boolean hasName() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <pre>
         * 文件名
         * </pre>
         *
         * <code>required string name = 2;</code>
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    name_ = s;
                }
                return s;
            }
        }

        /**
         * <pre>
         * 文件名
         * </pre>
         *
         * <code>required string name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasFile()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasName()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, file_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, file_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.meux.icarbonx.proto.ProtoServerConf.MultiFile)) {
                return super.equals(obj);
            }
            com.meux.icarbonx.proto.ProtoServerConf.MultiFile other = (com.meux.icarbonx.proto.ProtoServerConf.MultiFile) obj;

            boolean result = true;
            result = result && (hasFile() == other.hasFile());
            if (hasFile()) {
                result = result && getFile()
                        .equals(other.getFile());
            }
            result = result && (hasName() == other.hasName());
            if (hasName()) {
                result = result && getName()
                        .equals(other.getName());
            }
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasFile()) {
                hash = (37 * hash) + FILE_FIELD_NUMBER;
                hash = (53 * hash) + getFile().hashCode();
            }
            if (hasName()) {
                hash = (37 * hash) + NAME_FIELD_NUMBER;
                hash = (53 * hash) + getName().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.MultiFile parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.MultiFile parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.MultiFile parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.MultiFile parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.MultiFile parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.MultiFile parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.MultiFile parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.MultiFile parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.MultiFile parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.MultiFile parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.MultiFile parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.MultiFile parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.meux.icarbonx.proto.ProtoServerConf.MultiFile prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code PB_MEUMX.MultiFile}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:PB_MEUMX.MultiFile)
                com.meux.icarbonx.proto.ProtoServerConf.MultiFileOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.meux.icarbonx.proto.ProtoServerConf.internal_static_PB_MEUMX_MultiFile_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.meux.icarbonx.proto.ProtoServerConf.internal_static_PB_MEUMX_MultiFile_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.meux.icarbonx.proto.ProtoServerConf.MultiFile.class, com.meux.icarbonx.proto.ProtoServerConf.MultiFile.Builder.class);
            }

            // Construct using com.meux.icarbonx.proto.ProtoServerConf.MultiFile.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                file_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                name_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.meux.icarbonx.proto.ProtoServerConf.internal_static_PB_MEUMX_MultiFile_descriptor;
            }

            public com.meux.icarbonx.proto.ProtoServerConf.MultiFile getDefaultInstanceForType() {
                return com.meux.icarbonx.proto.ProtoServerConf.MultiFile.getDefaultInstance();
            }

            public com.meux.icarbonx.proto.ProtoServerConf.MultiFile build() {
                com.meux.icarbonx.proto.ProtoServerConf.MultiFile result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.meux.icarbonx.proto.ProtoServerConf.MultiFile buildPartial() {
                com.meux.icarbonx.proto.ProtoServerConf.MultiFile result = new com.meux.icarbonx.proto.ProtoServerConf.MultiFile(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.file_ = file_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.name_ = name_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.meux.icarbonx.proto.ProtoServerConf.MultiFile) {
                    return mergeFrom((com.meux.icarbonx.proto.ProtoServerConf.MultiFile) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.meux.icarbonx.proto.ProtoServerConf.MultiFile other) {
                if (other == com.meux.icarbonx.proto.ProtoServerConf.MultiFile.getDefaultInstance()) return this;
                if (other.hasFile()) {
                    setFile(other.getFile());
                }
                if (other.hasName()) {
                    bitField0_ |= 0x00000002;
                    name_ = other.name_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                if (!hasFile()) {
                    return false;
                }
                if (!hasName()) {
                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.meux.icarbonx.proto.ProtoServerConf.MultiFile parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.meux.icarbonx.proto.ProtoServerConf.MultiFile) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private com.google.protobuf.ByteString file_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>required bytes file = 1;</code>
             */
            public boolean hasFile() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required bytes file = 1;</code>
             */
            public com.google.protobuf.ByteString getFile() {
                return file_;
            }

            /**
             * <code>required bytes file = 1;</code>
             */
            public Builder setFile(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                file_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required bytes file = 1;</code>
             */
            public Builder clearFile() {
                bitField0_ = (bitField0_ & ~0x00000001);
                file_ = getDefaultInstance().getFile();
                onChanged();
                return this;
            }

            private java.lang.Object name_ = "";

            /**
             * <pre>
             * 文件名
             * </pre>
             *
             * <code>required string name = 2;</code>
             */
            public boolean hasName() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <pre>
             * 文件名
             * </pre>
             *
             * <code>required string name = 2;</code>
             */
            public java.lang.String getName() {
                java.lang.Object ref = name_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        name_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * 文件名
             * </pre>
             *
             * <code>required string name = 2;</code>
             */
            public com.google.protobuf.ByteString
            getNameBytes() {
                java.lang.Object ref = name_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    name_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * 文件名
             * </pre>
             *
             * <code>required string name = 2;</code>
             */
            public Builder setName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                name_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 文件名
             * </pre>
             *
             * <code>required string name = 2;</code>
             */
            public Builder clearName() {
                bitField0_ = (bitField0_ & ~0x00000002);
                name_ = getDefaultInstance().getName();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 文件名
             * </pre>
             *
             * <code>required string name = 2;</code>
             */
            public Builder setNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                name_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:PB_MEUMX.MultiFile)
        }

        // @@protoc_insertion_point(class_scope:PB_MEUMX.MultiFile)
        private static final com.meux.icarbonx.proto.ProtoServerConf.MultiFile DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new com.meux.icarbonx.proto.ProtoServerConf.MultiFile();
        }

        public static com.meux.icarbonx.proto.ProtoServerConf.MultiFile getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<MultiFile>
                PARSER = new com.google.protobuf.AbstractParser<MultiFile>() {
            public MultiFile parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new MultiFile(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<MultiFile> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<MultiFile> getParserForType() {
            return PARSER;
        }

        public com.meux.icarbonx.proto.ProtoServerConf.MultiFile getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_PB_MEUMX_FileUpload_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_PB_MEUMX_FileUpload_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_PB_MEUMX_MultiFile_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_PB_MEUMX_MultiFile_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\025pb_serverconfig.proto\022\010PB_MEUMX\"5\n\nFil" +
                        "eUpload\022\'\n\nmultiFiles\030\001 \003(\0132\023.PB_MEUMX.M" +
                        "ultiFile\"\'\n\tMultiFile\022\014\n\004file\030\001 \002(\014\022\014\n\004n" +
                        "ame\030\002 \002(\tB*\n\027com.meux.icarbonx.protoB\017Pr" +
                        "otoServerConf"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_PB_MEUMX_FileUpload_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_PB_MEUMX_FileUpload_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_PB_MEUMX_FileUpload_descriptor,
                new java.lang.String[]{"MultiFiles",});
        internal_static_PB_MEUMX_MultiFile_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_PB_MEUMX_MultiFile_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_PB_MEUMX_MultiFile_descriptor,
                new java.lang.String[]{"File", "Name",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
