server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    fetch-registry: false
    register-with-eureka: false
    server-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level: debug