server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.meux.icarbonx.entities
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    name: CELL-WORLD-USER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/userDB01?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: cell-world-user8002
    prefer-ip-address: true
logging:
  level: debug

info:
  app.name: meux.icarbonx
  company.name: www.icarbonx.com
