server:
  port: 8003

spring:
  application:
    name: CELL-WORLD-TEST-TOOLS
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: cell-world-test-tools8003
    prefer-ip-address: true

info:
  app.name: meux.icarbonx
  company.name: www.icarbonx.com

command:
  cmd: 1111
  sub_01: 1
  sub_02: 2
  sub_03: 3
  sub_04: 4
  sub_05: 5
  sub_06: 6
  sub_07: 7
  sub_08: 8
  sub_09: 9
  url: 192.168.150.72:9016