server:
  port: 8003

spring:
  application:
    name: CELL-WORLD-TEST-TOOLS
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: cell-world-test-tools8003
    prefer-ip-address: true

info:
  app.name: meux.icarbonx
  company.name: www.icarbonx.com

command:
  cmd: 1111
  sub_01: 0
  sub_02: 1
  sub_03: 2
  sub_04: 3
  sub_05: 4
  sub_06: 5
  sub_07: 6
  sub_08: 7
  sub_09: 8
  #url: http://10.0.66.13:80 线上

  url: http://127.0.0.1:9016

fileConfig:
  fileType: xls,bytes
  targetPath: D:\\cellword-config\
